In [1]:
import pandas as pd
import numpy as np
import math
import datetime as dt
from __future__ import division
import os

from matplotlib import pyplot as plt
%matplotlib inline
import missingno as msno

import category_encoders as ce
from sklearn import preprocessing

#library to get text similarity
import jellyfish

import pycountry
countries = {}
for country in pycountry.countries:
    countries[country.name] = country.alpha_2
    
import mpu    

import time
from datetime import date

pd.options.display.float_format = "{:.2f}".format

pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', -1)  # or 199
np.set_printoptions(threshold=np.nan)

In [2]:
df=pd.read_csv('/home/gjain/df_cat_enc_part1.csv')
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.head()

,timestamp,order_number,pay_id,affiliate,channelcode,local_trans_amt,trans_currency,nonmor,payment_method,eci,card_cvvmatch,card_avsmatch,customer_title,website_language,brand_continent,HasTicketInsurance,HasInsurance,HasBaggage,HasBaggage_Sale,HasAirhelpPlus,UsedVoucher,HasSP,gender,BookerCity,BookerCountry_Name,TotalAmountEUR,airline,Consolidator,OriginAirportCode,OriginCityName,OriginCountryName,OriginWorldPartName,OriginRegion,OriginSubRegion,DestinationAirportCode,DestinationCityName,DestinationCountryName,DestinationWorldPartName,DestinationRegion,DestinationSubRegion,Supplier,DomesticOrInternational,Haul,OneWayOrReturn,IsCombinedOneWay,IsITFare,TotalNumberOfPassengers,TotalNumberOfAdults,TotalNumberOfChildren,TotalNumberOfInfants,COW_NumberOfSegments,COW_NumberOfInboundSegments,COW_NumberOfOutboundSegments,NumberOfTickets,FareBaseAmount,HasSplitPnr,DeviceType,OrderDateBrandTime_Month,IsLowCost,target,email_user_id_len,email_domain,dob_month,bookerIsTravelAgency,successful_attempt_no,country_ip_flight_MatchScore,flight_distance,days_to_departure,vacation_length,cities_in_itinerary,cabin_class,name_len,weekend_booking,booking_daytime,bookerAgeBracket,email_sanity_score
0,2018-06-05 00:38:27 UTC,CHNL-11348593,4093147735,CHEAPTICKETSNL,Direct,759.31,EUR,0,IDEAL,3,2,2,7,NL,3,0,0,0,0,0,0,0,0,ROTTERDAM,Nederland,759.31,KLM,TXNL,NDJ,N'Djamena,Chad,Africa,0,Middle Africa,CDG,Paris,France,Europe,3,Western Europe,5,1,0,1,0,0,1,1,0,0,2,1,1,1,749.81,0,1,6,0,0,7,hotmail.com,8.00,0,1,0,9999.00,16,88,3,1,22,0,1,2,0.00
1,2018-11-07 15:43:09 UTC,VUS-8712542,4326174179,VAYAMAUS,Direct,879.78,USD,0,PAYPAL,5,2,2,5,EN,1,0,0,0,0,0,0,0,1,RICHMOND,USA,770.89,TURKISH AIRLINES,TXNL,NDJ,N'Djamena,Chad,Africa,0,Middle Africa,IAD,Washington,United States,North America,1,Northern America,5,1,0,0,0,0,1,1,0,0,2,0,2,1,879.78,0,1,11,0,0,6,hotmail.com,2.00,0,1,0,9375.21,27,0,3,1,15,0,3,4,0.46
2,2018-11-27 13:47:52 UTC,FL-15578084,4360626058,BUDGETAIRDE,swode,615.00,EUR,0,SOFORT,3,2,2,2,DE,3,0,0,0,0,0,0,0,1,BERLIN,Deutschland,-47.63,ETHIOPIAN AIRLINES,TXNL,NDJ,N'Djamena,Chad,Africa,0,Middle Africa,KRT,Khartoum,Sudan,Africa,0,Northern Africa,1,1,1,1,0,0,1,1,0,0,2,1,1,1,0.00,0,0,11,0,0,8,yahoo.com,1.00,0,1,0,9999.00,10,2,3,1,13,0,2,4,0.75
3,2018-09-24 08:36:41 UTC,KUSW-5029188,0000000000F8CE732C78,KAYAKUSWL,kayakuswld,830.52,USD,0,VISA,4,2,2,5,EN,1,0,0,0,0,0,0,0,1,CHESAPEAKE,USA,707.09,ROYAL AIR MAROC,TXNL,NDJ,N'Djamena,Chad,Africa,0,Middle Africa,NBO,Nairobi,Kenya,Africa,0,Eastern Africa,1,1,1,1,0,0,1,1,0,0,2,1,1,1,830.52,0,0,9,0,0,12,GMAIL.COM,12.00,0,1,0,9999.00,2,7,3,1,22,0,1,2,1.35
4,2018-11-29 22:33:36 UTC,BBE-1112497,4365153953,BUDGETAIRBE,tripadvisorbe,835.99,EUR,0,BMC,3,2,2,7,FR,3,0,0,0,0,0,0,1,0,MONS,Belgique,835.99,ETHIOPIAN AIRLINES,TXNL,NDJ,N'Djamena,Chad,Africa,0,Middle Africa,BRU,Brussels,Belgium,Europe,3,Western Europe,1,1,0,1,0,0,1,1,0,0,4,2,2,1,826.00,0,0,11,0,0,8,icloud.com,2.00,0,1,0,9999.00,20,19,5,1,17,0,1,3,0.66

In [5]:
#target, timestamp, order_number, pay_id not included below
#72 cols
all_cols=['affiliate','channelcode',
       'local_trans_amt', 'trans_currency', 'nonmor', 'payment_method', 'eci',
       'card_cvvmatch', 'card_avsmatch', 'customer_title', 'website_language',
       'brand_continent', 'HasTicketInsurance', 'HasInsurance', 'HasBaggage',
       'HasBaggage_Sale', 'HasAirhelpPlus', 'UsedVoucher', 'HasSP', 'gender',
       'BookerCity', 'BookerCountry_Name', 'TotalAmountEUR', 'airline',
       'Consolidator', 'OriginAirportCode', 'OriginCityName',
       'OriginCountryName', 'OriginWorldPartName', 'OriginRegion',
       'OriginSubRegion', 'DestinationAirportCode', 'DestinationCityName',
       'DestinationCountryName', 'DestinationWorldPartName',
       'DestinationRegion', 'DestinationSubRegion', 'Supplier',
       'DomesticOrInternational', 'Haul', 'OneWayOrReturn', 'IsCombinedOneWay',
       'IsITFare', 'TotalNumberOfPassengers', 'TotalNumberOfAdults',
       'TotalNumberOfChildren', 'TotalNumberOfInfants', 'COW_NumberOfSegments',
       'COW_NumberOfInboundSegments', 'COW_NumberOfOutboundSegments',
       'NumberOfTickets', 'FareBaseAmount', 'HasSplitPnr', 'DeviceType',
       'OrderDateBrandTime_Month', 'IsLowCost', 'email_user_id_len',
       'email_domain', 'dob_month', 'bookerIsTravelAgency',
       'successful_attempt_no', 'country_ip_flight_MatchScore',
       'flight_distance', 'days_to_departure', 'vacation_length',
       'cities_in_itinerary', 'cabin_class', 'name_len', 'weekend_booking',
       'booking_daytime', 'bookerAgeBracket', 'email_sanity_score']

loo_cols=['affiliate','channelcode','trans_currency','payment_method','eci','website_language','BookerCity',
          'BookerCountry_Name','airline',
          'Consolidator','OriginAirportCode','OriginCityName','OriginCountryName','OriginWorldPartName',
          'OriginSubRegion','DestinationAirportCode','DestinationCityName','DestinationCountryName',
          'DestinationWorldPartName','DestinationSubRegion','email_domain']
          
all_excl_loo_cols=list(set(all_cols)-set(loo_cols))+['target']
len(all_excl_loo_cols)

52